version: '3.7'

services:
   watchtower:
      image: containrrr/watchtower
      container_name: watchtower
      networks:
         - watchtower
      environment:
         - TZ=${TIMEZONE}
         - WATCHTOWER_MONITOR_ONLY=true
         - WATCHTOWER_CLEANUP=true
         - WATCHTOWER_SCHEDULE=0 0 1 * * MON
         - WATCHTOWER_NOTIFICATIONS=email
         - WATCHTOWER_NOTIFICATION_EMAIL_FROM=${EMAIL_FROM}
         - WATCHTOWER_NOTIFICATION_EMAIL_TO=${EMAIL_TO}
         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=${EMAIL_SERVER}
         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=${EMAIL_USER}
         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=${EMAIL_PW}
         - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=${EMAIL_PORT}
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      restart: unless-stopped

networks:
   watchtower:
      name: watchtower
