services:
   widmocc:
      image: mrvercetti/widmocc
      container_name: widmocc
      networks:
         - widmocc
         - proxy
      ports:
         - 1313:80
      restart: unless-stopped

networks:
   proxy:
      name: proxy
      external: true
   widmocc:
      name: widmocc
