services:
    joplin-db:
        image: postgres:16
        container_name: joplin-db
        volumes:
            - ${APPS_DIR}/joplin/postgres:/var/lib/postgresql/data
        networks:
            - joplin
        ports:
            - "5432:5432"
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=${JOPLIN_POSTGRES_PASSWORD}
            - POSTGRES_USER=${JOPLIN_POSTGRES_USER}
            - POSTGRES_DB=${JOPLIN_POSTGRES_DB}

    joplin:
        image: joplin/server
        container_name: joplin
        networks:
            - proxy
            - joplin
        ports:
            - "22300:22300"
        environment:
            - APP_PORT=22300
            - APP_BASE_URL=${JOPLIN_BASE_URL}
            - DB_CLIENT=pg
            - POSTGRES_PASSWORD=${JOPLIN_POSTGRES_PASSWORD}
            - POSTGRES_DATABASE=${JOPLIN_POSTGRES_DB}
            - POSTGRES_USER=${JOPLIN_POSTGRES_USER}
            - POSTGRES_PORT=5432
            - POSTGRES_HOST=joplin-db
        depends_on:
            - joplin-db
        restart: unless-stopped

networks:
  proxy:
    external:
        name: proxy
  joplin:
    name: joplin
