services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma
    ports:
      - 3111:3001
    volumes:
      - ${APPS_DIR}/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
      - monitoring
    restart: unless-stopped

  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    ports:
      - "8283:8080" # webapp
      - "8286:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${APPS_DIR}/scrutiny/config:/opt/scrutiny/config
      - ${APPS_DIR}/scrutiny/influxdb:/opt/scrutiny/influxdb
    networks:
      - monitoring
    devices:
      - "/dev/sda"
      - "/dev/sdb"
      - "/dev/sdc"
      - "/dev/nvme0"
    restart: unless-stopped

  beszel:
    image: henrygd/beszel
    container_name: beszel
    networks:
      - monitoring
    ports:
      - 8091:8090
    volumes:
      - ${APPS_DIR}/beszel:/beszel_data
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/parity1/.beszel:/extra-filesystems/sdd1:ro
      - /mnt/disk1/.beszel:/extra-filesystems/sdb1:ro
      - /mnt/disk2/.beszel:/extra-filesystems/sda1:ro
      - /mnt/disk3/.beszel:/extra-filesystems/sdc1:ro
    environment:
      - PORT=45876
      # Do not remove quotes around the key
      - KEY=${BESZEL_SSH_KEY}
    restart: unless-stopped

  dozzle:
    image: amir20/dozzle
    container_name: dozzle
    networks:
      - monitoring
    ports:
      - 8081:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
   proxy:
      name: proxy
      external: true
   monitoring:
      name: monitoring
