services:
   ogt-fs:
      image: halverneus/static-file-server
      container_name: ogt-fs
      networks:
         - ogt-fs
         - proxy
      volumes:
         - ${DATA_DIR}/ogt-fs:/content/files
      environment:
         - FOLDER=/content/files
      ports:
         - 8097:8080
      restart: unless-stopped

networks:
   proxy:
      external:
         name: proxy
   ogt-fs:
      name: ogt-fs
